#!/bin/bash

echo "openssl genrsa -des3 -out server.key 1024"
openssl genrsa -des3 -out server.key 1024

echo "openssl req -new -key server.key -out server.csr"
openssl req -new -key server.key -out server.csr

echo "cp server.key server.key.org"
cp server.key server.key.org

echo "openssl rsa -in server.key.org -out server.key"
openssl rsa -in server.key.org -out server.key

echo "openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt"
openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt

echo "openssl pkcs12 -export -in server.crt -inkey server.key -out server.pfx"
openssl pkcs12 -export -in server.crt -inkey server.key -out server.pfx

